plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dhaksha.live'
    compileSdk 34

    defaultConfig {
        applicationId 'com.dhaksha.live'
        minSdk 21
        targetSdk 34
        versionCode 2
        versionName '2.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    def media3 = '1.4.1'
    implementation "androidx.media3:media3-exoplayer:$media3"
    implementation "androidx.media3:media3-exoplayer-hls:$media3"
    implementation "androidx.media3:media3-exoplayer-rtsp:$media3"
    implementation "androidx.media3:media3-ui:$media3"
}
